### ISSUE TITLE
Error: InvalidUnit

### ISSUE THREAD

**Issue by comporell** [NativeScript/tailwind#152]
hello, 
I use "tailwindcss": "^3.1.8" and "@nativescript/tailwind": "^2.0.0",

after angular 14.2.0 upgrade I started having this error below:

`ERROR in ./src/app.android.scss
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: InvalidUnit
    at G:\GitHub\hw\src\app.android.scss:2021:3
    at parseSingleAnimationShorthand (G:\GitHub\hw\node_modules\@hookun\parse-animation-shorthand\cjs\parseSingleAnimationShorthand.js:44:23)
    at Declaration (G:\GitHub\hw\node_modules\@nativescript\tailwind\src\expandAnimations.js:14:24)
    at LazyResult.visitTick (G:\GitHub\hw\node_modules\postcss\lib\lazy-result.js:502:16)
    at LazyResult.runAsync (G:\GitHub\hw\node_modules\postcss\lib\lazy-result.js:410:30)
    at async Object.loader (G:\GitHub\hw\node_modules\postcss-loader\dist\index.js:95:14)
 @ ./src/main.ts 2:0-28`

the app does not run due to the error. The only possible fix that I 'we found is to remove this line from _app-common.scss :

`@import '@nativescript/theme/default'; `

Do you have any other suggestions to fix this? As removing that line mess up my template.

Best Regards,

**Comment by comporell** [comment]
looks like its due to an error with animation naming. created a workaround PR 
https://github.com/NativeScript/tailwind/pull/153
